version: "3.9"
services:
  web:
    build: .
    depends_on:
      - postgres
    expose:
      - 443
    ports:
      - 443:443
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/public/build
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fourth_wall_cache
      - POSTGRES_HOST=zoomingthroughthefourthwall-postgres-1
  postgres:
    image: "postgres:latest"
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fourth_wall_cache
      - TZ=GMT+12
      - PGTZ=GMT+12
    volumes:
      - ./startup.sql:/docker-entrypoint-initdb.d/startup.sql
      